
# Change from a 0-based index to 1-based index for easier access
# Run "<prefix>:move-window -r" to re-number everything
set-option -g base-index 1
set-option -g pane-base-index 1

# Enable mouse support
set-option -g mouse on

# Update scrollback buffer (in lines). Default is 2000 lines
set-option -g history-limit 5000

# Remove tmux specific info from title
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"

# Open new window/splits in current working directory
bind c new-window -c "#{pane_current_path}"
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Enable focus events for server
set-option -s focus-events on

# Allow more key combos and escape sequences (e.g. for neovim)
set-option -s extended-keys on

# Disable waiting time when pressing <Esc>, for smoother neovim experience
# Disable if differentiation between function and meta key combo is needed
set-option -s escape-time 0

# Update display of status bar
#set-option -g status-justify centre # or absolute-center
#set-option -g status-left "#S"
#set-option -g status-right "#h"

# Reload tmux config
unbind r
bind r source-file ~/.tmux.conf
